//! Embedded dashboard assets, generated by `build.rs` into `dashboard_embed.rs`.
//!
//! The dashboard is compiled into the binary at build time (see `http/build.rs`)
//! so a release of aria-router is self-contained. At runtime we prefer an
//! on-disk `dashboard/dist` (dev override / `ARIA_ROUTER_DASHBOARD`) and fall
//! back to these embedded bytes, then to the API-only router.

include!(concat!(env!("OUT_DIR"), "/dashboard_embed.rs"));

use std::sync::Arc;

use axum::body::Body;
use axum::http::{header, StatusCode, Uri};
use axum::response::Response;
use axum::routing::get;
use axum::Router;
use bytes::Bytes;

use crate::AppState;

/// Whether the binary was compiled with an embedded dashboard.
pub fn has_dashboard() -> bool {
    DASHBOARD_HAS
}

/// Management router backed by the embedded dashboard assets.
pub fn mgmt_router_with_embedded_dashboard(state: Arc<AppState>) -> Router {
    crate::mgmt_api_router(state).fallback(get(serve_embedded))
}

/// Combined management router: prefer an on-disk `dashboard/dist` (dev
/// override), then the embedded assets, then the API-only router.
pub fn mgmt_router_serve_dashboard(state: Arc<AppState>) -> Router {
    if let Some(dir) = crate::resolve_dashboard_dir() {
        crate::mgmt_router_with_dashboard(state, dir)
    } else if has_dashboard() {
        mgmt_router_with_embedded_dashboard(state)
    } else {
        crate::mgmt_router(state)
    }
}

async fn serve_embedded(uri: Uri) -> Response {
    let key = normalize(uri.path());
    if let Some(data) = lookup(&key) {
        return bytes_response(data, content_type(&key));
    }
    // SPA fallback: unknown paths without a file extension serve index.html;
    // missing asset files (with an extension) return 404.
    if key.contains('.') {
        return Response::builder()
            .status(StatusCode::NOT_FOUND)
            .body(Body::from("not found"))
            .unwrap();
    }
    bytes_response(DASHBOARD_INDEX, "text/html; charset=utf-8")
}

fn lookup(key: &str) -> Option<&'static [u8]> {
    DASHBOARD_FILES
        .iter()
        .find(|f| f.path == key)
        .map(|f| f.data)
}

fn normalize(path: &str) -> String {
    let mut p = percent_decode(path.trim_start_matches('/'));
    if p.is_empty() {
        return "index.html".to_string();
    }
    if p.ends_with('/') {
        p.push_str("index.html");
    }
    p
}

fn percent_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let (Some(h), Some(l)) = (hex_val(bytes[i + 1]), hex_val(bytes[i + 2])) {
                out.push(h * 16 + l);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn hex_val(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

fn bytes_response(data: &'static [u8], ct: &'static str) -> Response {
    Response::builder()
        .header(header::CONTENT_TYPE, ct)
        .body(Body::from(Bytes::from_static(data)))
        .unwrap()
}

fn content_type(path: &str) -> &'static str {
    match path.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("js") | Some("mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") | Some("map") => "application/json; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("ico") => "image/x-icon",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("ttf") => "font/ttf",
        Some("txt") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}
